### ISSUE TITLE
Set up redirects to WAYF UI

### ISSUE THREAD

**Issue by tomboone** [WRLC/catalog-redirects#1]
Where institution is know from existing record, catalog-redirects already redirects to the proper institutional Alma correctly.

However, when the institution isn't known from the existing record, users should be redirected to a WAYF UI so they can select their institution manually.

Lines 56 & 61 in `app.py` are where the redirects should be placed:

```python
return(redirect(view.format('')))
```

**Comment by tomboone** [comment]
@dongourley Does the WAYF UI already exist in another place, or should I simply add another route to this Flask app for institution selection?

**Comment by dongourley** [comment]
I think the wayf menu exists in the catalog-redirects app, but it may be in the nginx/html config...not sure. Where we need it of course is in the [aladin-redirects](https://github.com/WRLC/aladin-redirects) app and I thought this app..catalog-redirects...would be an example for that.

**Comment by tomboone** [comment]
Ah okay. Yet again I got the two repos confused. I'll switch over to [aladin-redirects](https://github.com/WRLC/aladin-redirects).
